#!/bin/bash

# Copyright(c) 2010.
#    * Jonas Forsberg 
#    * Jimmy Hedman 
#
# This file may be licensed under the terms of of the
# GNU General Public License Version 2 (the ``GPL'').
#
# Software distributed under the License is distributed
# on an ``AS IS'' basis, WITHOUT WARRANTY OF ANY KIND, either
# express or implied. See the GPL for the specific language
# governing rights and limitations.
#
# You should have received a copy of the GPL along with this
# program. If not, go to http://www.gnu.org/licenses/gpl.html
# or write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.




#%# family=test
#%# capabilities=autoconf

SYSPATH="/sys/kernel/mm/ksm/"
KSMFILES="pages_shared pages_unshared pages_volatile pages_sharing"



do_ () {
    # Test if sys-files for KSM are present
    for f in $KSMFILES
    do
        if [ ! -f "${SYSPATH}${f}" ]; then
            echo "Unable to find file: ${SYSPATH}${f}" >&2
        fi
    done
    echo shared.value $(cat ${SYSPATH}pages_shared)
    echo unshared.value $(cat ${SYSPATH}pages_unshared)
    echo volatile.value $(cat ${SYSPATH}pages_volatile)
    echo sharing.value $(cat ${SYSPATH}pages_sharing)
}

do_autoconf () {
    for f in $KSMFILES
    do
        if [ ! -f "${SYSPATH}${f}" ]; then
            echo "no (Unable to find file: ${SYSPATH}${f})" 
            exit 0
        fi
    done
    echo "yes"
}

do_config () {
        cat <<EOF
graph_title KSM pages
graph_info Memory pages used by KSM
graph_vlabel Memory pages
graph_category system
graph_args --base 1000 -l 0
graph_scale yes
shared.label Shared
shared.info Number of shared memory pages
shared.type GAUGE
shared.draw AREA
unshared.label Unshared
unshared.info Number of memory pages aviable for sharing
unshared.type GAUGE
unshared.draw STACK
volatile.label Volatile
volatile.info Non shareble memory pages
volatile.type GAUGE
volatile.draw STACK
sharing.label Sharing
sharing.info An indication of memory pages savings
sharing.type GAUGE
sharing.draw LINE2
EOF
}

do_$1

